package Slytherin.visao;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Slytherin.controle.ControleCarrinho;
import Slytherin.entidade.Carrinho;
import Slytherin.entidade.ItemPedido;

/**
 *
 * @author Lukas e Rayssa
 */
public class CarrinhoCompras extends javax.swing.JFrame {
    
    private final ControleCarrinho conCar = new ControleCarrinho();
    private ItemPedido escolhido = null;
    
    /**
     * Cria um novo form Carrinho
     */
    public CarrinhoCompras() {
        initComponents();
        this.setTitle("Livraria Slytherin");
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_itens = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_sifra = new javax.swing.JLabel();
        lbl_preco = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_mais = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        btn_continuar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 246, 252));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(242, 246, 252));

        tb_itens.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_itens.setGridColor(new java.awt.Color(93, 194, 176));
        tb_itens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_itensMouseClicked(evt);
            }
        });
        tb_itens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_itensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_itens);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Subtotal : ");

        lbl_sifra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_sifra.setText("R$");

        lbl_preco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_preco.setText("120,00");

        btn_limpar.setBackground(new java.awt.Color(16, 187, 211));
        btn_limpar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpar.setText("Limpar carrinho");
        btn_limpar.setBorder(null);
        btn_limpar.setBorderPainted(false);
        btn_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_limparMouseExited(evt);
            }
        });
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(16, 187, 211));
        btn_menos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btn_menos.setForeground(new java.awt.Color(255, 255, 255));
        btn_menos.setText("-");
        btn_menos.setBorder(null);
        btn_menos.setBorderPainted(false);
        btn_menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menosMouseExited(evt);
            }
        });
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_mais.setBackground(new java.awt.Color(16, 187, 211));
        btn_mais.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btn_mais.setForeground(new java.awt.Color(255, 255, 255));
        btn_mais.setText("+");
        btn_mais.setBorder(null);
        btn_mais.setBorderPainted(false);
        btn_mais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_maisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_maisMouseExited(evt);
            }
        });
        btn_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maisActionPerformed(evt);
            }
        });

        btn_adicionar.setBackground(new java.awt.Color(16, 187, 211));
        btn_adicionar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_adicionar.setForeground(new java.awt.Color(255, 255, 255));
        btn_adicionar.setText("Adicionar livros");
        btn_adicionar.setBorder(null);
        btn_adicionar.setBorderPainted(false);
        btn_adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adicionarMouseExited(evt);
            }
        });
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_remover.setBackground(new java.awt.Color(16, 187, 211));
        btn_remover.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_remover.setForeground(new java.awt.Color(255, 255, 255));
        btn_remover.setText("Remover item ");
        btn_remover.setBorder(null);
        btn_remover.setBorderPainted(false);
        btn_remover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_removerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_removerMouseExited(evt);
            }
        });
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        btn_continuar.setBackground(new java.awt.Color(16, 187, 211));
        btn_continuar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_continuar.setForeground(new java.awt.Color(255, 255, 255));
        btn_continuar.setText("Continuar");
        btn_continuar.setBorder(null);
        btn_continuar.setBorderPainted(false);
        btn_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_continuarMouseExited(evt);
            }
        });
        btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(49, 59, 69));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Meu Carrinho");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(308, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_sifra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_preco)
                                .addGap(58, 58, 58)
                                .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_continuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_adicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_preco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sifra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        if(escolhido != null) {
            conCar.retirarItem(escolhido.getLivro().getIsbn());
            preencherTabela();
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Volte mais tarde...");
    }//GEN-LAST:event_btn_continuarActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        if(escolhido != null) {
            int quantidade = escolhido.getQuantidade() - 1;
            conCar.alterarItem(escolhido.getLivro().getIsbn(), String.valueOf(quantidade));
            preencherTabela();
        }
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maisActionPerformed
        if(escolhido != null) {
            int quantidade = escolhido.getQuantidade() + 1;
            conCar.alterarItem(escolhido.getLivro().getIsbn(), String.valueOf(quantidade));
            preencherTabela();
        }
    }//GEN-LAST:event_btn_maisActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        conCar.limparCarrinho();
        preencherTabela();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void tb_itensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_itensMouseClicked
        int linha;
        if (evt.getClickCount() == 1) {
            linha = tb_itens.getSelectedRow();
            escolhido = Carrinho.getItens().get(linha);
            System.out.println(escolhido.getLivro().getTitulo());
        }
    }//GEN-LAST:event_tb_itensMouseClicked

    private void tb_itensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_itensKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_itensKeyPressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MousePressed

    private void btn_menosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menosMouseEntered
        // TODO add your handling code here:
        btn_menos.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_menosMouseEntered

    private void btn_menosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menosMouseExited
        // TODO add your handling code here:
        btn_menos.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_menosMouseExited

    private void btn_maisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maisMouseEntered
        // TODO add your handling code here:
        btn_mais.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_maisMouseEntered

    private void btn_maisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maisMouseExited
        // TODO add your handling code here:
        btn_mais.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_maisMouseExited

    private void btn_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseEntered
        // TODO add your handling code here:
        btn_limpar.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_limparMouseEntered

    private void btn_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseExited
        // TODO add your handling code here:
         btn_limpar.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_limparMouseExited

    private void btn_removerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removerMouseEntered
        // TODO add your handling code here:
        btn_remover.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_removerMouseEntered

    private void btn_removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removerMouseExited
        // TODO add your handling code here:
        btn_remover.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_removerMouseExited

    private void btn_adicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionarMouseEntered
        // TODO add your handling code here:
        btn_adicionar.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_adicionarMouseEntered

    private void btn_adicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionarMouseExited
        // TODO add your handling code here:
        btn_adicionar.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_adicionarMouseExited

    private void btn_continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseEntered
        // TODO add your handling code here:
        btn_continuar.setBackground(new java.awt.Color(93,194,176));
    }//GEN-LAST:event_btn_continuarMouseEntered

    private void btn_continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseExited
        // TODO add your handling code here:
        btn_continuar.setBackground(new java.awt.Color(16,187,211));
    }//GEN-LAST:event_btn_continuarMouseExited

    @SuppressWarnings("UseOfObsoleteCollectionType")
    public void preencherTabela() {
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        //Cabeçalho
        Vector cabecalho = new Vector();
        cabecalho.add("Item");
        cabecalho.add("Preço");
        cabecalho.add("Quantidade");
        cabecalho.add("Subtotal parcial");
        
        //Itens
        Vector dados = new Vector();
        Vector item;
        float subtotal = 0f;

        for (ItemPedido ix : Carrinho.getItens()) {
            item = new Vector();
            item.add(ix.getLivro().getTitulo());
            item.add(formato_grana.format(ix.getSubtotal()/ix.getQuantidade())); //Divide subtotal por quantidade
            item.add(ix.getQuantidade());
            item.add(formato_grana.format(ix.getSubtotal()));
            subtotal += ix.getSubtotal(); //Soma subtotal para exibir
            dados.add(item);
        }
        
        DefaultTableModel modeloTabela = new DefaultTableModel();
        modeloTabela.setDataVector(dados, cabecalho);
        tb_itens.setModel(modeloTabela);

        //muda tamanho das colunas
        tb_itens.getColumnModel().getColumn(0).setMaxWidth(450);
        tb_itens.getColumnModel().getColumn(1).setMaxWidth(90);
        tb_itens.getColumnModel().getColumn(2).setMaxWidth(105);
        tb_itens.getColumnModel().getColumn(3).setMaxWidth(150);
        
        //Vê o preço subtotal
        lbl_preco.setText(formato_grana.format(subtotal));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_continuar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_mais;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_remover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_sifra;
    private javax.swing.JTable tb_itens;
    // End of variables declaration//GEN-END:variables
}
